### ISSUE TITLE
what is the recommended Python and Torch versions

### ISSUE THREAD

**Issue by HaoRayx** [Awesome3DGS/libgs#1]
hello，thanks for the excellent job! I 'd like to ask about the recommended Python and Torch versions

**Comment by gqk** [comment]
Hi @HaoRayx, 

Thank you for your attention! 

We have been using PyTorch 2.0/2.1 and Python 3.9/3.10 in our environment. Newer versions are expected to be compatible, though we haven’t tested them yet. If you encounter any issues, please don’t hesitate to reach out—we’d be happy to work with you to resolve them.

Best regards
